### ISSUE TITLE
Grif Prevention Placeholder expansion wont load

### ISSUE THREAD

**Issue by matthewtrains** [pixar02/Expansions#2]
> [23:25:54] [Server thread/INFO]: Matthewtrains issued server command: /papi reload
> [23:25:54] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: vault
> [23:25:54] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: mvdw
> [23:25:54] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: luckperms
> [23:25:54] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player
> [23:25:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.10.6
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [server.jar:git-Spigot-800b93f-8160e29]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoClassDefFoundError: me/ryanhamshire/GriefPrevention/GriefPrevention
at com.pixar02.papi.expansion.GriefPreventionExpansion.register(GriefPreventionExpansion.java:50) ~[?:?]
at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:114) ~[?:?]
at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:174) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPIPlugin.reloadConf(PlaceholderAPIPlugin.java:186) ~[?:?]
at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:261) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Spigot-800b93f-8160e29]
... 17 more
Caused by: java.lang.ClassNotFoundException: me.ryanhamshire.GriefPrevention.GriefPrevention
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
at com.pixar02.papi.expansion.GriefPreventionExpansion.register(GriefPreventionExpansion.java:50) ~[?:?]
at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:114) ~[?:?]
at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:174) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPIPlugin.reloadConf(PlaceholderAPIPlugin.java:186) ~[?:?]
at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:261) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Spigot-800b93f-8160e29]
... 17 more

**Comment by pixar02** [comment]
You need to have GriefPrevention installed

**Comment by matthewtrains** [comment]
I do?

**Comment by pixar02** [comment]
The word expansion states that it builds on something. Since PlaceholderAPI and Spigot itself, don't have any griefprevention, it must be an extra plugin. So it's normal that expansion doesn't work when the core (on what it builds/depends) isn't there.

**Comment by matthewtrains** [comment]
would it be possible its not working bc of a out of date grifprevention?

**Comment by matthewtrains** [comment]
> [19:23:58] [Craft Scheduler Thread - 17/ERROR]: [FeatherBoard] Error in placeholder: {griefprevention_currentclaim_width}
> [19:23:58] [Craft Scheduler Thread - 17/ERROR]: [FeatherBoard] Error in placeholder: {griefprevention_claims}
> [19:24:07] [Server thread/INFO]: Matthewtrains issued server command: /griefprevention
> [19:24:11] [Server thread/INFO]: Matthewtrains issued server command: /griefprevention:abandonallclaims
> [19:24:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'griefprevention:abandonallclaims' in plugin GriefPrevention v16.13.0 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [server.jar:git-Spigot-800b93f-8160e29]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> [19:24:23] [Server thread/INFO]: Matthewtrains issued server command: /plugman enable GriefPrevention
> [19:24:23] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v16.13.0
> [19:24:23] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader GriefPrevention v16.13.0
> [19:24:23] [Server thread/INFO]: [GriefPrevention] Siege Configuration: Material not found: LONG_GRASS.
> [19:24:23] [Server thread/INFO]: [GriefPrevention] Siege Configuration: Material not found: THIN_GLASS.
> [19:24:23] [Server thread/INFO]: [GriefPrevention] Siege Configuration: Material not found: WOOD.
> [19:24:23] [Server thread/INFO]: [GriefPrevention] Siege Configuration: Material not found: WOOL.
> [19:24:23] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.
> [19:24:23] [Server thread/INFO]: [GriefPrevention] ERROR: Unable to connect to database. Check your config file settings.
> [19:24:23] [Server thread/INFO]: [GriefPrevention] Because there was a problem with the database, GriefPrevention will not function properly. Either update the database config settings resolve the issue, or delete those lines from your config.yml so that GriefPrevention can use the file system to store data.
> [19:24:23] [Server thread/WARN]: java.sql.SQLException: No suitable driver found for localhost:3306
> [19:24:23] [Server thread/WARN]: at java.sql.DriverManager.getConnection(DriverManager.java:689)
> [19:24:23] [Server thread/WARN]: at java.sql.DriverManager.getConnection(DriverManager.java:208)
> [19:24:23] [Server thread/WARN]: at me.ryanhamshire.GriefPrevention.DatabaseDataStore.refreshDataConnection(DatabaseDataStore.java:629)
> [19:24:23] [Server thread/WARN]: at me.ryanhamshire.GriefPrevention.DatabaseDataStore.initialize(DatabaseDataStore.java:77)
> [19:24:23] [Server thread/WARN]: at me.ryanhamshire.GriefPrevention.DatabaseDataStore.<init>(DatabaseDataStore.java:58)
> [19:24:23] [Server thread/WARN]: at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:276)
> [19:24:23] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [19:24:23] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
> [19:24:23] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
> [19:24:23] [Server thread/WARN]: at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62)
> [19:24:23] [Server thread/WARN]: at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127)
> [19:24:23] [Server thread/WARN]: at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
> [19:24:23] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [19:24:23] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
> [19:24:23] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)
> [19:24:23] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
> [19:24:23] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [19:24:23] [Server thread/INFO]: [GriefPrevention] Disabling GriefPrevention v16.13.0
> [19:24:23] [Server thread/ERROR]: Error occurred while disabling GriefPrevention v16.13.0 (Is it up to date?)
java.lang.NullPointerException: null
at me.ryanhamshire.GriefPrevention.GriefPrevention.onDisable(GriefPrevention.java:3244) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:438) ~[server.jar:git-Spigot-800b93f-8160e29]
at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:293) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [server.jar:git-Spigot-800b93f-8160e29]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by matthewtrains** [comment]
Out of cerosity what database does grifprevention make?

**Comment by pixar02** [comment]
16.13 is the latest version
Looks like it's using SQL database

**Comment by matthewtrains** [comment]
Yeah so this used to run awhile ago when my dev was active and im here trying to get it backup and running and i found out there is a database for it

**Comment by matthewtrains** [comment]
so im assumeing thats the issue

**Comment by pixar02** [comment]
it is the issue...
I don't know what you have on your server...
But there should be a startup script somewhere...

**Comment by matthewtrains** [comment]
o ok ill look

**Comment by matthewtrains** [comment]
so i looked at your doccumentation and updated the database info and it appears to be working now
